### ISSUE TITLE
How did you make your display picture?

### ISSUE THREAD

**Issue by alexbooker** [arthurvr/ama#25] opened 2015-07-10 07:49 UTC
Hey, @arthurvr,

Congratulations on joining the @yeoman team! 

My question is: How did you make your display picture? If someone else made it, who? I really like it.

**Comment by arthurvr** [comment] 2015-07-10 09:47
Closing as this is a duplicate of #26.

**Closed by arthurvr** 2015-07-10 09:47 UTC

**Comment by alexbooker** [comment] 2015-07-10 11:47
Um. I have no idea how I ended up posting this twice.
